name: hello

on: 
  push:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-22.04
    container: rust:1.64.0-slim
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: first step
        run: echo "Starting tests" && ls