name: hello

on: 
  push:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-22.04
    container: rust:1.64.0-slim
    steps:
      - name: Fetch code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Print
        run: echo "Starting tests" && ls
      - name: Exec tests
        run: cargo test